name: crystal
description: Make your own Magic

version: 1.0.0+1

environment:
    sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:

    # Flutter
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    # Redux
    redux: ^3.0.0
    flutter_redux: ^0.5.2
    redux_logging: ^0.3.0
    redux_thunk: ^0.2.0

    # Utils
    intl: 0.15.7
    cupertino_icons: ^0.1.2
    csv: 4.0.1

dev_dependencies:
    intl_translation: 0.17.2

flutter:

    uses-material-design: true

    assets:
      - assets/emojis/animal/
      - assets/emojis/blood/
      - assets/emojis/drink/
      - assets/emojis/extra/
      - assets/emojis/food/
      - assets/emojis/gender/
      - assets/emojis/scenery/
      - assets/emojis/weather/
      - assets/names/

    fonts:
    -   family: NatureBeauty
        fonts:
        -   asset: assets/fonts/Nature-Beauty.ttf

    -   family: OpenSans
        fonts:
          -   asset: assets/fonts/OpenSans-Regular.ttf
          -   asset: assets/fonts/OpenSans-Bold.ttf
